blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Questions / ä½¿ç”¨é—®é¢˜
    url: https://github.com/antdv-next/antdv-next/discussions
    about: è‹¥ä¸ºä½¿ç”¨é—®é¢˜ï¼Œè¯·ä¼˜å…ˆåœ¨ Discussions æé—®ï¼ˆæ”¯æŒ English / ä¸­æ–‡ï¼‰ã€‚
  - name: ğŸ“– Documentation / æ–‡æ¡£
    url: https://antdv-next.com
    about: æäº¤ Bug ä¹‹å‰è¯·å…ˆæŸ¥é˜…æ–‡æ¡£ã€‚
